name: CI

on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches:
      - 'feature/*'

concurrency: ${{ github.ref }}

jobs:
  # Lint job runs on a single Node version (18.x here, but pick whichever you want)
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          # Removed the 'cache' lines completely

      - name: Install Yarn 4 globally & enable Corepack
        run: |
          npm install -g corepack yarn@4.6.0
          corepack enable
          yarn --version  # Debug to confirm it’s 4.6.0

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

  # Build and test across multiple Node versions
  build-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '18.x', '20.x', '23.x' ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Removed the 'cache' lines completely

      - name: Install Yarn 4 globally & enable Corepack
        run: |
          npm install -g corepack yarn@4.6.0
          corepack enable
          yarn --version  # Debug to confirm it’s 4.6.0

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Test project
        run: yarn test
