name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test
- name: Report status
  uses: actions/github-script@v5
  with:
    script: |
      const core = require('@actions/core');
      const github = require('@actions/github');
      const context = github.context;

      const octokit = github.getOctokit(core.getInput('github-token'));
      await octokit.rest.repos.createCommitStatus({
        owner: context.repo.owner,
        repo: context.repo.repo,
        sha: context.sha,
        state: 'success',
        context: 'CI Build',
        description: 'CI build and tests passed',
      });
    github-token: ${{ secrets.GITHUB_TOKEN }}
